### ISSUE TITLE
python-3.7.0 incompatibility: webbrowser.register()

### ISSUE THREAD

**Issue by 0-wiz-0** [caseychu/spotify-backup#13]
python-3.7 changed the calling convention of the function.
3.6.6 (https://docs.python.org/3.6/library/webbrowser.html):
````

webbrowser.register(name, constructor, instance=None)

    Register the browser type name. Once a browser type is registered, the get() function can return a controller for that browser type. If instance is not provided, or is None, constructor will be called without parameters to create an instance when needed. If instance is provided, constructor will never be called, and may be None.

    This entry point is only useful if you plan to either set the BROWSER variable or call get() with a nonempty argument matching the name of a handler you declare.
````
3.7.0 (https://docs.python.org/3.7/library/webbrowser.html):
````
webbrowser.register(name, constructor, instance=None, *, preferred=False)

    Register the browser type name. Once a browser type is registered, the get() function can return a controller for that browser type. If instance is not provided, or is None, constructor will be called without parameters to create an instance when needed. If instance is provided, constructor will never be called, and may be None.

    Setting preferred to True makes this browser a preferred result for a get() call with no argument. Otherwise, this entry point is only useful if you plan to either set the BROWSER variable or call get() with a nonempty argument matching the name of a handler you declare.

    Changed in version 3.7: preferred keyword-only parameter was added.
````

This breaks spotify-backup:
````
Traceback (most recent call last):
  File "./spotify-backup.py", line 170, in <module>
    main()
  File "./spotify-backup.py", line 137, in main
    spotify = SpotifyAPI.authorize(client_id='5c098bcc800e45d49e476265bc9b6934', scope='playlist-read-private')
  File "./spotify-backup.py", line 61, in authorize
    'redirect_uri': 'http://127.0.0.1:{}/redirect'.format(SpotifyAPI._SERVER_PORT)
  File "/usr/pkg/lib/python3.7/webbrowser.py", line 75, in open
    register_standard_browsers()
  File "/usr/pkg/lib/python3.7/webbrowser.py", line 567, in register_standard_browsers
    cmd = _synthesize(cmdline, -1)
  File "/usr/pkg/lib/python3.7/webbrowser.py", line 116, in _synthesize
    register(browser, None, controller, update_tryorder)
TypeError: register() takes from 2 to 3 positional arguments but 4 were given
````

**Comment by caseychu** [comment]
Thanks for pointing this out. Seems like this was a bug in Python itself: https://bugs.python.org/issue31014
