### ISSUE TITLE
TypeError when processing playlist "Your Time Capsule"

### ISSUE THREAD

**Issue by erikw** [caseychu/spotify-backup#14]
First - thanks for this great script! I run it from [a cronjob ](https://github.com/erikw/dotfiles/blob/personal/bin/spotify-backup.sh)regularly, as my playlists are very dear to me and I can not afford to let Spotify own them. Thanks!

So for the issue:

The Spotify meta playlist "Your Time Capsule" causes the following error:

```
$ spotify-backup.py --format txt playlist.txt
[08:14:09] Loading playlist: Your Time Capsule (55 songs)
Traceback (most recent call last):
  File "/Users/erikw/src/github.com/caseychu/spotify-backup/spotify-backup.py", line 170, in <module>
    main()
  File "/Users/erikw/src/github.com/caseychu/spotify-backup/spotify-backup.py", line 161, in main
    uri=track['track']['uri'],
TypeError: 'NoneType' object is not subscriptable
2 tries left.
```

**Comment by schuft69** [comment]
got the same with:
[08:07:42] Loading playlist: 16 Horsepower – Yours Truly (25 songs)
Traceback (most recent call last):
  File "/home/steffen/bin/spotify-backup.py", line 170, in <module>
    main()
  File "/home/steffen/bin/spotify-backup.py", line 161, in main
    uri=track['track']['uri'],
TypeError: 'NoneType' object is not subscriptable

**Comment by erikw** [comment]
I don't get this error anymore. It somehow disappeared.
