### ISSUE TITLE
Bug with liked songs

### ISSUE THREAD

**Issue by lamorton** [caseychu/spotify-backup#28]
I'm getting the following when attempting to run the script with liked songs enabled (but not without):

```
Traceback (most recent call last):

  File "<ipython-input-12-263240bbee7e>", line 1, in <module>
    main()

  File "C:\Users\lucas\Documents\Code\Python\Spotify_Backup\spotify-backup.py", line 176, in main
    logging.info('Loading playlist: {name} ({tracks[total]} songs)'.format(**playlist))

TypeError: list indices must be integers or slices, not str
```

**Comment by caseychu** [comment]
Thanks for reporting -- could you try again with latest master?

**Comment by lamorton** [comment]
That did the trick! Thanks.
